# Generated by Django 6.0.2 on 2026-03-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='departement',
        ),
    ]
