# Generated by Django 6.0.2 on 2026-03-23 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_departement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(choices=[('RH', 'RH'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Commercial', 'Commercial'), ('Production', 'Production'), ('Logistique', 'Logistique'), ('Qualité', 'Qualité')], max_length=15, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(blank=True, editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('birth_date', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('security_social_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'Emlpoyee',
            },
        ),
        migrations.CreateModel(
            name='SivilStatus',
            fields=[
                ('status', models.CharField(choices=[('Célibataire', 'Célibataire'), ('Marié(e)', 'Marié(e)'), ('Divorcé(e)', 'Divorcé(e)'), ('Veuf/Veuve', 'Veuf/Veuve')], max_length=15, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Sivil Statuses',
                'db_table': 'SIVIL_STATUS',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.employee')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'Salary',
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contract_Type', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage'), ('Alternance', 'Alternance')], max_length=15)),
                ('Hire_Date', models.DateField(blank=True)),
                ('End_Date', models.DateField(blank=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employee')),
            ],
            options={
                'db_table': 'ContractType',
            },
        ),
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Title', models.CharField(max_length=15)),
                ('Profession_Status', models.CharField(blank=True, choices=[('Cadre', 'Cadre'), ('Non-Cadre', 'Non-Cadre')], max_length=10)),
                ('Seniority', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Activity_Status', models.CharField(blank=True, choices=[('Actif', 'Actif'), ('Sorti', 'Sorti')], max_length=10)),
                ('Contract_Type', models.ForeignKey(db_column='Contract_Type', on_delete=django.db.models.deletion.PROTECT, to='home.contracttype')),
                ('Department_Name', models.ForeignKey(db_column='Department_Name', on_delete=django.db.models.deletion.PROTECT, to='home.department')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employee')),
            ],
            options={
                'db_table': 'JobInfo',
            },
        ),
        migrations.CreateModel(
            name='LeaveInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Leave_Date', models.DateField()),
                ('Leave_Reason', models.CharField(blank=True, max_length=100)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employee')),
            ],
            options={
                'db_table': 'LeaveInfo',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.PROTECT, to='home.sivilstatus'),
        ),
        migrations.AddConstraint(
            model_name='contracttype',
            constraint=models.UniqueConstraint(fields=('employee_id', 'Contract_Type'), name='pk_contracttype_employee_contract'),
        ),
        migrations.AddConstraint(
            model_name='jobinfo',
            constraint=models.UniqueConstraint(fields=('employee_id', 'Job_Title'), name='pk_jobinfo_employee_title'),
        ),
        migrations.AddConstraint(
            model_name='leaveinfo',
            constraint=models.UniqueConstraint(fields=('employee_id', 'Leave_Date'), name='pk_leaveinfo_employee_date'),
        ),
    ]
