# Generated by Django 6.0.2 on 2026-03-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_department_employee_sivilstatus_salary_contracttype_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='Employee',
        ),
    ]
