# Generated by Django 6.0.2 on 2026-03-23 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_employee_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttype',
            name='employee_id',
            field=models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='home.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, db_column='employee_id', editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='employee_id',
            field=models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='home.employee'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='employee_id',
            field=models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='home.employee'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='employee_id',
            field=models.OneToOneField(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.employee'),
        ),
    ]
